"$schema" = "./node_modules/wrangler/config-schema.json"
name = "automata-editor"
main = ".velte-kit/cloudflare/_worker.js"
# Set this to today's date
compatibility_date = "2026-02-18"
compatibility_flags = ["nodejs_als"]
workers_dev = false

[route]
pattern = "automata.seagrass.co.za/*"
zone_name = "automata.seagrass.co.za"
